about_resource: dockerfile_parse-1.2.0-py2.py3-none-any.whl
checksum_md5: b72d75c6c8b4a42f5f85d44fd91a8abd
checksum_sha1: 5498b8e6c981c40fd5b08e315f547a13a7ded936
copyright: Copyright (c) Jiri Popelka <jpopelka@redhat.com>
description: Python library for Dockerfile manipulation
download_url: https://files.pythonhosted.org/packages/53/83/e9579a25c26bc8e1a6033e46e756e18c25caa05bfc421673d99d1af2efab/dockerfile_parse-1.2.0-py2.py3-none-any.whl
homepage_url: https://github.com/containerbuildsystem/dockerfile-parse
license_expression: bsd-new
name: dockerfile-parse
package_url: pkg:pypi/dockerfile-parse@1.2.0
primary_language: Python
type: pypi
version: 1.2.0
