about_resource: dockerfile-parse-1.2.0.tar.gz
checksum_md5: 42efe5c354c830045b756e76eb4f84d5
checksum_sha1: f1950e29f22b81782264657cb92df9d0e295e52e
copyright: Copyright (c) Jiri Popelka <jpopelka@redhat.com>
description: Python library for Dockerfile manipulation
download_url: https://files.pythonhosted.org/packages/d0/f6/8eb044e3837f6da0a85d9f73158104fecdab68bc86a83625b1e398963ed3/dockerfile-parse-1.2.0.tar.gz
homepage_url: https://github.com/containerbuildsystem/dockerfile-parse
license_expression: bsd-new
name: dockerfile-parse
package_url: pkg:pypi/dockerfile-parse@1.2.0
primary_language: Python
type: pypi
version: 1.2.0
